#!/bin/bash

mysqladmin -f -u root -POLOPOLO drop events
mysqladmin -u root -POLOPOLO create events
mysqlaccess -U --spassword=POLOPOLO localhost damogar events --password=events

echo ".";

mysql -u damogar -pevents events < ../sql/linux-events.sql
