#!/bin/bash

mysqladmin -f -u root -pPOLOPOLO drop events
mysqladmin -u root -pPOLOPOLO create events
mysqlaccess -U --spassword=POLOPOLO localhost damogar events --password=events

echo ".";

mysql -u damogar -pevents events < ../sql/linux-events.sql
