#!/bin/bash

mysqladmin -f -u events -pevents drop events
mysqladmin -u events -pevents create events
mysqlaccess -U --spassword=events localhost events events --password=events

echo ".";

mysql -u events -pevents events < ../sql/linux-events.sql
